# Linux file to EXPORT_SYMBOL all of the Xilinx entries.
#obj-$(CONFIG_XILINX_EDK) := xilinx_syms.o

# The Xilinx OS independent code.
obj-$(CONFIG_XILINX_EDK) += xbasic_types.o  xipif_v1_23_b.o \
			 xpacket_fifo_v2_00_a.o xpacket_fifo_l_v2_00_a.o \
			 xdma_channel.o  xversion.o xdma_channel_sg.o \
			 xdmav3.o xdmav3_intr.o xdmav3_sg.o xdmav3_simple.o
