#define LSP_BUILD_ID   "0801921"
#define LSP_REVISION   "1"
#define LSP_NAME       "ti-davinci_evm-arm_v5t_le"
#define LSP_BOARD_NAME "TI DaVinci - DM644x Processor (little endian)"
#define LSP_MVL_ARCH   "arm_v5t_le"
